// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ7pJXlprh9Z6isjCc8nODthn8RDWnnnU',
    appId: '1:299886509638:web:18c190d90ebf031c25d447',
    messagingSenderId: '299886509638',
    projectId: 'findyourveto',
    authDomain: 'findyourveto.firebaseapp.com',
    storageBucket: 'findyourveto.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWHNSxi8miA3AWRiqxqWJblXffOIejqvk',
    appId: '1:299886509638:android:e9e6cce65ebae68025d447',
    messagingSenderId: '299886509638',
    projectId: 'findyourveto',
    storageBucket: 'findyourveto.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoNGqHXaGq-5IbPwsXJIBhL-Y65RkoUGE',
    appId: '1:299886509638:ios:00e734eed4117f7825d447',
    messagingSenderId: '299886509638',
    projectId: 'findyourveto',
    storageBucket: 'findyourveto.firebasestorage.app',
    iosBundleId: 'com.example.findyourveto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoNGqHXaGq-5IbPwsXJIBhL-Y65RkoUGE',
    appId: '1:299886509638:ios:00e734eed4117f7825d447',
    messagingSenderId: '299886509638',
    projectId: 'findyourveto',
    storageBucket: 'findyourveto.firebasestorage.app',
    iosBundleId: 'com.example.findyourveto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ7pJXlprh9Z6isjCc8nODthn8RDWnnnU',
    appId: '1:299886509638:web:2f30db9a75e8d3a925d447',
    messagingSenderId: '299886509638',
    projectId: 'findyourveto',
    authDomain: 'findyourveto.firebaseapp.com',
    storageBucket: 'findyourveto.firebasestorage.app',
  );
}
